### ISSUE TITLE
 Type definitions missing nested function

### ISSUE THREAD

**Issue by charlescrain** [justinwoo/purescript-ohyes#1]
I noticed that if I make a definition:

```purescript
module Generate (main) where


import Prelude

import Data.Foldable (intercalate)
import Node.Encoding (Encoding(..))
import Node.FS.Sync (writeTextFile)
import OhYes (generateTS)
import Text.Prettier (defaultOptions, format)
import Type.Proxy (Proxy(..))

main :: Effect Unit
main = do
  writeTextFile UTF8 "./ts/src/purs/Types.ts" values
  where
    values = format defaultOptions $ intercalate "\n"
      [  generateTS "simpleFn" (Proxy :: Proxy (String -> String) ]
```
The resulting type is:

```typescript
export type simpleFn = (a: string) => string;
```

When calling the `simpleFn` in typescript, 
```typescript
simpleFn("hi")
``` 
`"hi"` is applied to the function but a subsequent `()` is needed, i.e. 

```typescript
simpleFn("hi")() // causes type script compiler error because it believes `simpleFn("hi")` is a string.
``` 

If we add an extra: `() =>` then the function signature in typescript matches:

```typescript
export type simpleFn = (a: string) => () => string;
```
and 
```typescript
simpleFn("hi")()
```
If you're fine with this solution I'll make a PR and add this to the

Function and Fn2 typeclasses

Great library btw!

**Comment by justinwoo** [comment]
The extra thunk should only be there if the function if the result is an Effect: https://pursuit.purescript.org/packages/purescript-effect/2.0.0/docs/Effect.Uncurried

Otherwise if `simpleFn` is a pure function, it will work.

I don't think I understand though, where have you defined simpleFn here? You're just passing a proxy of `String -> String`?

**Comment by charlescrain** [comment]
Oh awesome! My mistake, I wasn't adding the `Effect` to my type! Works as it should with the appropriate types

**Comment by charlescrain** [comment]
Also thanks for directing me to the Effect.Uncurried library, it was exactly what I was missing
