### ISSUE TITLE
Request to add Int instance for HasTSRep 

### ISSUE THREAD

**Issue by epicallan** [justinwoo/purescript-ohyes#3]
I am curious if there is any reason for not including an `Int` instance for HasTSRep, incase there isn't I could submit a PR adding it. 

Secondly, I am also curious whether you would be open to me opening a PR updating prettier once this gets merged. 
https://github.com/gcanti/purescript-prettier/pull/5

**Comment by justinwoo** [comment]
I don't think "Int" has any real representation in JS as it can be easily broken. That said, this "library" is just some template for you to fork from and integrate into your own codebase, so you can make your own decision on that.

**Comment by justinwoo** [comment]
The formatting update is probably not strictly necessary either, as this is mostly an archive more than anything.

**Comment by epicallan** [comment]
Ok makes sense. Thanks
